version: 0.2
phases:
  pre_build:
    commands:
      - echo "Installing Java 17..."
      - sudo apt update
      - sudo apt install -y openjdk-17-jdk
      - java -version
      - echo "Installing Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building the Java Maven project..."
      - mvn clean install
artifacts:
  files: '**/*'

